***BACKUP***

CREATE TABLE T_ARTIKEL_TMP (NAME TEXT NOT NULL, BARCODE TEXT NOT NULL);
INSERT INTO T_ARTIKEL_TMP (NAME, BARCODE) SELECT NAME, BARCODE FROM T_ARTIKEL;

***RESTORE***
INSERT INTO T_ARTIKEL (NAME, BARCODE) SELECT NAME, BARCODE FROM T_ARTIKEL_TMP;
