DROP TABLE IF EXISTS T_PREIS;
DROP TABLE IF EXISTS T_ARTIKEL;
DROP TABLE IF EXISTS T_MARKE;
DROP TABLE IF EXISTS T_HAENDLER;

CREATE TABLE T_HAENDLER (
       HAENDLER_ID INTEGER NOT NULL CONSTRAINT PK_T_HAENDLER PRIMARY KEY AUTOINCREMENT
     , HAENDLERNAME VARCHAR(100) NOT NULL
);

CREATE TABLE T_MARKE (
       MARKE_ID INTEGER NOT NULL CONSTRAINT PK_T_MARKE PRIMARY KEY AUTOINCREMENT
     , MARKENNAME VARCHAR(100) NOT NULL
);

CREATE TABLE T_ARTIKEL (
       ARTIKEL_ID INTEGER NOT NULL CONSTRAINT PK_T_ARTIKEL PRIMARY KEY AUTOINCREMENT
     , NAME TEXT NOT NULL
     , BARCODE TEXT NOT NULL
     , FOTO TEXT
     , MARKE_ID INTEGER
     , CONSTRAINT FK_T_ARTIKEL_1 FOREIGN KEY (MARKE_ID)
                  REFERENCES T_MARKE (MARKE_ID)
);

CREATE TABLE T_PREIS (
       PREIS INTEGER
     , ARTIKEL_ID INTEGER NOT NULL
     , HAENDLER_ID INTEGER NOT NULL
     , CONSTRAINT FK_T_PREIS_1 FOREIGN KEY (ARTIKEL_ID)
                  REFERENCES T_ARTIKEL (ARTIKEL_ID)
     , CONSTRAINT FK_T_PREIS_2 FOREIGN KEY (HAENDLER_ID)
                  REFERENCES T_HAENDLER (HAENDLER_ID)
);

